### ISSUE TITLE
Support for different config suffixes

### ISSUE THREAD

**Issue by RayJason** [antfu/eslint-flat-config-viewer#1]
### Clear and concise description of the problem

My eslint config names `.eslintrc`. It'll report an error: 
```
[nuxt] [request error] [unhandled] [500] Cannot find module '**/eslint.config.js'
```
Obviously, only configuration files with the suffix config.js are currently supported.

### Suggested solution

Support for configuration files with different suffixes.
https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file-formats

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sorry no, this project is tend to, and would only work with the new flat config format: https://eslint.org/docs/latest/use/configure/configuration-files-new
