### ISSUE TITLE
Support loading eslint.config.mjs or eslint.config.ts as flat config file

### ISSUE THREAD

**Issue by christopher-buss** [antfu/eslint-flat-config-viewer#13]
### Clear and concise description of the problem

As a developer using eslint-flat-config-viewer, I'd like for eslint.config.ts files to be automatically detected.

### Suggested solution

Built-in support for other eslint configs file types be available (as per your eslint-ts-patch).

### Alternative

Alternatively, a README on how to manually set the file extension so that I can support a non-js file (ts in my case) easily (as I'm aware it first checks  the `process.env.ESLINT_CONFIG` variable (I will admit, I did not find out how to set this while running `npx eslint-flat-config-viewer`. ).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Supported in v0.1.4. Thanks
