### ISSUE TITLE
Add a button to collapse/expand all config items at once

### ISSUE THREAD

**Issue by stefanobartoletti** [antfu/eslint-flat-config-viewer#18]
### Clear and concise description of the problem

At the moment, individual config items can be expanded/collapsed by clicking on their titles.

I think it would be a nice addition to have a button at the top of the page to collapse/expand all of them at once. 

When a user adds custom config, they are placed at the bottom of the page. Collapsing all items at once could help to navigate to that without too much scrolling, and also to see at-a-glance a list of all used config items.

Thanks!

### Suggested solution

Add a button to collapse/expand all items

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Makes sense, PR welcome :)

**Comment by stefanobartoletti** [comment]
I'm quite busy with regular work at the moment, I may try to have a look at this when I will have more spare time.

I'm not jealous though of the idea, if somebody else happens to read this and wants to give it a try, be my guest :)

**Comment by stefanobartoletti** [comment]
Thanks for this 🙏
