### ISSUE TITLE
Mark imported config

### ISSUE THREAD

**Issue by erosman** [antfu/eslint-flat-config-viewer#19]
### Clear and concise description of the problem

- **Configs**
Use a reference instead of `anonymous #1` e.g. ` js.configs.recommended,` or `@eslint/js.configs.recommended,`

```js
import js from "@eslint/js"; 
// ---
export default [
  js.configs.recommended, 

  // ---
]:
```

- **Rules**
It would be useful to mark rules that are imported e.g. `js.configs.recommended` so that they can be differentiated from the manually added `rules`.

### Suggested solution

as above

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I am trying to push that direction: https://github.com/eslint/eslint/issues/18231

The config-viewer gets the data from runtime, so we can't possibly know the source for each config. That would require configs to provide the name properly later.

**Comment by erosman** [comment]
## configs.recommended

[ESLint Config Viewer] Config payload
https://github.com/antfu/eslint-flat-config-viewer/blob/fa224fdf10c53c48b86c6d0a80df95051806128b/composables/payload.ts#L22

Data example
```json
    "constructor-super": {
      "type": "problem",
      "docs": {
        "description": "Require `super()` calls in constructors",
        "recommended": true,
        "url": "https://eslint.org/docs/latest/rules/constructor-super"
      },
      "name": "constructor-super",
      "plugin": "eslint"
    },
```

It would be helpful to mark rules with ` "recommended": true,` to show that they are part of `configs.recommended`.
