### ISSUE TITLE
Provide an option to toggle rule by clicking on it in list

### ISSUE THREAD

**Issue by mnik01** [antfu/eslint-flat-config-viewer#3]
### Clear and concise description of the problem

It would be cool to have an option to toggle rule by clicking on it in list. And maybe add ability to configure rule. The error or warning level toggler for example

### Suggested solution

To add/remove related rule in `eslint.config.js`. 

### Additional context

<img width="967" alt="image" src="https://github.com/antfu/eslint-flat-config-viewer/assets/39025497/d05560e1-0195-43b6-a8d1-8c0c4248da4c">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't honestly think it's possible, as JS is very dynamic, we can't determine where the rule comes from or even write it back
