### ISSUE TITLE
Flag deprecated rules

### ISSUE THREAD

**Issue by pnodet** [antfu/eslint-flat-config-viewer#8]
### Clear and concise description of the problem

Following this blog post [eslint.org/blog/deprecating-formatting-rules](https://eslint.org/blog/2023/10/deprecating-formatting-rules) I was migrating from the old rules to stylistic plugin.

Even if this is maybe not the best example, it made me think about having deprecated rules shown as such in the viewer you made.

No idea if this is possible, just a "would be cool" feature.

### Suggested solution

/

### Alternative

/

### Additional context

/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, PR welcome :)
